spring.application.name=sdlc-devops

spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise_sdlc_devops
spring.datasource.username=postgres
spring.datasource.password=chandu@23777

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true